apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: user-service
build:
  artifacts:
    - image: camelcasemm/user-service
      runtimeType: jvm
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: user-service
        chartPath: helm
        namespace: devenv
        valuesFiles:
          - helm/values.yaml
        version: 0.0.0
        setValues:
          spring.profile: "devenv"

portForward:
  - resourceType: service
    resourceName: user-service
    namespace: devenv
    port: 8080
    localPort: 8080
