spring:
  application:
    name: user
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true

management:
  metrics:
    enable:
      all: true
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
      
---
spring:
  config:
    activate:
      on-profile: devenv
  datasource:
    url: jdbc:postgresql://db-devenv-postgresql:5432/devenvdb
    driver-class-name: org.postgresql.Driver
    username: devenv
    password: devenv

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect